import {
  ArrowDownToLine,
  ArrowLeftRight,
  ChevronDown,
  ChevronUp,
  Circle,
  Contrast,
  Copy,
  Droplets,
  Ellipsis,
  Eraser,
  Eye,
  EyeOff,
  FlipHorizontal2,
  FlipVertical2,
  Layers,
  Menu,
  Minus,
  Move,
  PaintBucket,
  Pencil,
  Pipette,
  Plus,
  Redo2,
  RotateCwSquare,
  SlidersHorizontal,
  Slash,
  Square,
  SquareDashed,
  Trash2,
  Undo2,
  X,
  type LucideIcon,
} from 'lucide-react';

/** Interface icons, from Lucide (ISC, https://lucide.dev). */
export const ICONS = {
  move: Move,
  select: SquareDashed,
  pencil: Pencil,
  eraser: Eraser,
  bucket: PaintBucket,
  line: Slash,
  rect: Square,
  ellipse: Circle,
  shade: Contrast,
  blur: Droplets,
  picker: Pipette,
  undo: Undo2,
  redo: Redo2,
  plus: Plus,
  minus: Minus,
  trash: Trash2,
  eye: Eye,
  eyeOff: EyeOff,
  up: ChevronUp,
  down: ChevronDown,
  duplicate: Copy,
  merge: ArrowDownToLine,
  more: Ellipsis,
  swap: ArrowLeftRight,
  menu: Menu,
  layers: Layers,
  panel: SlidersHorizontal,
  close: X,
  rotate: RotateCwSquare,
  // Lucide names these after the axis line: the vertical line mirrors left-right.
  flipH: FlipVertical2,
  flipV: FlipHorizontal2,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS | 'logo';

/** The Baipix logo, a 13×17 "B" drawn in the text color (white on dark, black on light). */
export const LOGO = {
  width: 13,
  height: 17,
  d: 'M2.314 16.822V14.586H0V2.288H2.314V0H10.01V2.288H12.35V7.774H10.01V9.048H12.35V14.586H10.01V16.822H2.314ZM3.068 13.598H9.256V10.01H4.602V6.812H9.256V3.25H3.068V13.598Z',
};
